/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-12-02 14:58:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Filmbooking.*;
import java.util.ArrayList;
import org.apache.catalina.connector.Request;

public final class film_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      Filmbooking.filmBean film_list = null;
      synchronized (application) {
        film_list = (Filmbooking.filmBean) _jspx_page_context.getAttribute("film_list", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (film_list == null){
          film_list = new Filmbooking.filmBean();
          _jspx_page_context.setAttribute("film_list", film_list, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      Filmbooking.seatBean seat_list = null;
      synchronized (application) {
        seat_list = (Filmbooking.seatBean) _jspx_page_context.getAttribute("seat_list", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (seat_list == null){
          seat_list = new Filmbooking.seatBean();
          _jspx_page_context.setAttribute("seat_list", seat_list, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      Filmbooking.member person = null;
      synchronized (session) {
        person = (Filmbooking.member) _jspx_page_context.getAttribute("person", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (person == null){
          person = new Filmbooking.member();
          _jspx_page_context.setAttribute("person", person, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("film_list"), request);
      out.write('\r');
      out.write('\n');
      Filmbooking.resvBean resv_list = null;
      synchronized (application) {
        resv_list = (Filmbooking.resvBean) _jspx_page_context.getAttribute("resv_list", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (resv_list == null){
          resv_list = new Filmbooking.resvBean();
          _jspx_page_context.setAttribute("resv_list", resv_list, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("resv_list"), request);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>영화 상영 리스트</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<h3>현재 상영 리스트</h3>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t");

			if (person.getName_mem() != null) {
		
      out.write("\r\n");
      out.write("\t\t[<a href=change.jsp>회원 정보 변경(");
      out.print(person.getName_mem());
      out.write(")\r\n");
      out.write("\t\t</a>] [<a href=\"control.jsp?action=member&member=logout\">로그아웃 </a>]\r\n");
      out.write("\t\t");

			} else {
		
      out.write("[<a href=login.jsp>로그인</a>]\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=100>타이틀</td>\r\n");
      out.write("\t\t\t\t<td width=100>관람가</td>\r\n");
      out.write("\t\t\t\t<td width=100>총 좌석수</td>\r\n");
      out.write("\t\t\t\t<td width=100>상영기간</td>\r\n");
      out.write("\t\t\t\t<td width=100>예매</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				for (film movie : (ArrayList<film>) film_list.getDBList()) {
					if ((person.getName_mem() != null) && movie.getAge_phase() > person.getAge_mem())
						continue;
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=100>");
      out.print(movie.getFilm_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=100>");
      out.print(movie.getAge_phase() + "세 이용가");
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=100>");
      out.print(movie.getSeat_num() + "석");
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=100>");
      out.print(movie.getDate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"control.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"member\" value=\"main\" /> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"hidden\" name=\"action\" value=\"member\" /> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"submit\" value=\"선택\"> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"select\" value=");
      out.print(movie.getId_film());
      out.write(" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
