/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-12-02 11:46:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Filmbooking.*;

public final class pay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      Filmbooking.resvBean resv_list = null;
      synchronized (application) {
        resv_list = (Filmbooking.resvBean) _jspx_page_context.getAttribute("resv_list", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (resv_list == null){
          resv_list = new Filmbooking.resvBean();
          _jspx_page_context.setAttribute("resv_list", resv_list, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      Filmbooking.member person = null;
      synchronized (session) {
        person = (Filmbooking.member) _jspx_page_context.getAttribute("person", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (person == null){
          person = new Filmbooking.member();
          _jspx_page_context.setAttribute("person", person, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("<title>예매 내역</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<h3>예매 내역</h3>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t[<a href=film_list.jsp>메인 화면으로</a>]\r\n");
      out.write("\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=200 align=\"center\">영화 제목</td>\r\n");
      out.write("\t\t\t\t<td width=150 align=\"center\">상영 기간</td>\r\n");
      out.write("\t\t\t\t<td width=70 align=\"center\">예약일</td>\r\n");
      out.write("\t\t\t\t<td width=80 align=\"center\">좌석 번호</td>\r\n");
      out.write("\t\t\t\t<td width=100 align=\"center\">예약 상황</td>\r\n");
      out.write("\t\t\t\t<td width=150 align=\"center\">결제 및 취소</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				int id = person.getId_mem();
				for (resv book : resv_list.getDBList()) {
					if (book.getId_mem() == id) {
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=200 align=\"center\">");
      out.print(book.getFilm_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=150 align=\"center\">");
      out.print(book.getDate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=70 align=\"center\">");
      out.print(book.getResv_date());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=100 align=\"center\">");
      out.print(book.getSeat_no() + 1);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=50 align=\"center\">\r\n");
      out.write("\t\t\t\t\t");

						if (!book.isStatus())
									out.print("-");
								else
									out.print("결재 완료");
					
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td colspan=2 align=\"center\" width=150>\r\n");
      out.write("\t\t\t\t\t");

						if (!book.isStatus()) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"card.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"결재\" /> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"rid\" value=");
      out.print(book.getId_resv());
      out.write(" />\r\n");
      out.write("\t\t\t\t\t</form> ");

 	}
 
      out.write("\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"control.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"얘매내역 삭제\" /> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"action\" value=\"resv\" /> <input type=\"hidden\" name=\"oper\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"cancel\" /> <input type=\"hidden\" name=\"rid\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=");
      out.print(book.getId_resv());
      out.write(" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				}
				}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
